### ISSUE TITLE
configure some sort of City scope auth

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#3]
either 

* LDAP 
* Google Auth

**Comment by hunterowens** [comment]
honestly, after our LDAP experimentation, I'm increasingly fine with github based auth, as it sounds like we'll be moving to github enterprise soon and we want people to use git to version their notebooks, so this makes a github account a preqreq of an account on this system.

**Comment by ian-r-rose** [comment]
An update on this. @jaylenw and I got Azure AD OAuth up and running. Configuration for this can be found in the `azure-ad` branch (encrypted, mostly), as well as in the Azure portal. There are still a few kinks to work out, but if we want to go down this path, I think it should be pretty doable. In particular
1. AD provided some user names that were a bit unexpected, mine was `ian rose`, rather than my email or ID. Where did that name come from?
1. We can add users on thee JHub side or on the AD side. What is better for our needs?
