### ISSUE TITLE
plots don't show up by default without running %matplotlib inline

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/citywide-jupyterhub#36]

**Comment by ian-r-rose** [comment]
There is quite a lot of history here, as matplotlib support in the notebook predates almost everything else in the ecosystem, and so its handling is a bit bespoke compared to other somewhat more modern approaches. For that reason, there is the extra step to tell matplotlib the environment in which you are doing the plotting.

 That said, I think we can configure this so that it is the default option.

**Comment by hunterowens** [comment]
Yeah, i think having it run by default is the most user friendly behavior,
but might cause other underdesired behavior

**Comment by ian-r-rose** [comment]
I think it should be pretty safe.
